export const eventsData = [
  {
    date: new Date(2023, 5, 18).toISOString(),
    id: 1,
    image: {
      alt: 'matrix-mini-kiki-ball',
      src: 'https://i.ibb.co/7bPrMvy/matrix-mini-kiki-ball.jpg',
    },
    path: "/matrix2023",
    title: 'MATRIX',
    type: 'Mini Kiki Ball',
  },
  {
    date: new Date(2023, 6, 2).toISOString(),
    id: 2,
    image: {
      alt: 'pride-kiki-ball',
      src: 'https://i.ibb.co/bXj2PRK/pride-kiki-ball.jpg',
    },
    path: "/pride2023",
    title: 'Pride',
    type: 'Kiki Ball',
  },
  {
    date: new Date(2023, 7, 18).toISOString(),
    id: 3,
    image: {
      alt: 'erotik-kiki-ball',
      src: 'https://i.ibb.co/M5Dz8Cw/erotik-kiki-ball.jpg',
    },
    path: "/erotik2023",
    title: 'Erotik',
    type: 'Kiki Ball',
  },
  {
    date: new Date(2023, 8, 16).toISOString(),
    id: 4,
    image: {},
    path: "/houseofprince&antonio2023",
    title: 'House of Prince & Antonio',
    type: 'Kiki Ball',
  },
  {
    date: new Date(2023, 9, 15).toISOString(),
    id: 5,
    image: {
      alt: 'dynasty-kiki-ball',
      src: 'https://i.ibb.co/1JcSR6L/dynasty-kiki-ball.jpg',
    },
    path: "/dinasty2023",
    title: 'Dynasty',
    type: 'Kiki Ball',
  },
  {
    date: new Date(2023, 10, 18).toISOString(),
    id: 6,
    image: {},
    path: "/houseofmattel2023",
    title: 'House of Mattel',
    type: 'Kiki Ball',
  },
  {
    date: new Date(2023, 11, 16).toISOString(),
    id: 7,
    image: {},
    path: "/endofyear2023",
    title: 'Fin de Año',
    type: 'Kiki Ball',
  },
];
