import {
  closeSidebar,
  fetchPlaylists,
  openSidebar,
  setCurrentVideo,
  setEventsData,
  setEventInfo,
  setHideLoading,
  setIsAnimating,
  setSearchedWord,
  setShowCalendar,
  setShowDictionary,
  setShowEvent,
  setWasFound,
  setWordsData,
} from './slices';
import { store } from './store';

export {
  closeSidebar,
  fetchPlaylists,
  openSidebar,
  setCurrentVideo,
  setEventsData,
  setEventInfo,
  setHideLoading,
  setIsAnimating,
  setSearchedWord,
  setShowDictionary,
  setShowCalendar,
  setShowEvent,
  setWasFound,
  setWordsData,
  store,
};
